/*
  _____       _                           ___   ___ ___  _  _                                            
 |  __ \     | |                         |__ \ / _ \__ \| || |                                           
 | |__) |___ | |__   ___   ___ ___  _ __    ) | | | | ) | || |_                                          
 |  _  // _ \| '_ \ / _ \ / __/ _ \| '_ \  / /| | | |/ /|__   _|                                         
 | | \ \ (_) | |_) | (_) | (_| (_) | | | |/ /_| |_| / /_   | |                                           
 |_|  \_\___/|_.__/ \___/ \___\___/|_| |_|____|\___/____|  |_|                                           
                     _____ _                    _____ _                   _        _____          _      
                    / ____| |                  / ____| |                 (_)      / ____|        | |     
                   | (___ | |_ ___  ___ _ __  | |    | |__   __ _ ___ ___ _ ___  | |     ___   __| | ___ 
                    \___ \| __/ _ \/ _ \ '__| | |    | '_ \ / _` / __/ __| / __| | |    / _ \ / _` |/ _ \
                    ____) | ||  __/  __/ |    | |____| | | | (_| \__ \__ \ \__ \ | |___| (_) | (_| |  __/
                   |_____/ \__\___|\___|_|     \_____|_| |_|\__,_|___/___/_|___/  \_____\___/ \__,_|\___|
                                                                                                         */
/**
  ******************************************************************************
  * @file    system_start.c/h
  * @brief   整车初始化
  * @version 1.0
  * @par Change Log：
  * 		Date				Version				Author					Description
	*			23.11.11			V1.0					Gsx							Creator
	* @note
	*			说明：本项目为风暴战队Robocon2024初代舵轮底盘代码，使用新一代AC6编译器
	*						加速编译的同时，支持C，C++混合编程
	*						优化了CAN的收发函数，电机信息处理，顺便把祖传包浆PID翻新了一下-_-
	*
	*
  ******************************************************************************
  * @attention
  * 
  * if you had modified this file, please make sure your code does not have any 
  * bugs, update the version Number, write dowm your name and the date. The most
  * important thing is make sure the users will have clear and definite under-
  * standing through your new brief.
  ******************************************************************************
*/
#include "system_start.h"
#include "system_datapool.h"
#include "system_os.h"
#include "bsp_usart.h"
#include "bsp_timer.h"
#include "bsp_can.h"
#include "drv_dr16.h"
#include "drv_motor.h"
#include "mod_Chassis.h"
#include "math_my_pid.h"

static void dr16_call_back(uint8_t *buf, uint16_t len);
static void User_CAN1_RxCpltCallback(CAN_RxBuffer *CAN_RxMessage);
static void User_CAN2_RxCpltCallback(CAN_RxBuffer *CAN_RxMessage);

Chassis_Control_t	chassis_control = {0};
/*遥控解包任务*/
void RC_Task(void *p_arg);
TaskHandle_t RC_Task_Handler;
/*底盘任务*/
TaskHandle_t Chassis_Task_Handler;
void Chassis_Task(void *p_arg);
#define CHASSIS_TIM	1

/**
	* @brief  系统初始化
	* @retval None
	*/
void System_Init(void)
{
	bsp_Timer_Init(1);
	bsp_uart4_Init(Uart4_Rx_Buff[0], Uart4_Rx_Buff[1], UART4_RX_BUFFER_SIZE, dr16_call_back);
	bsp_can_Init(&hcan1,2,User_CAN1_RxCpltCallback);
  bsp_can_Init(&hcan2,2,User_CAN2_RxCpltCallback);
	getMicroTick_regist(Get_SystemTimer);
	
	 /*CAN滤波器配置*/
	/*CAN1*/
	CAN_Filter_Mask_Config(&hcan1, CanFilter_0|CanFifo_0|Can_STDID|Can_DataType,0x201,0x3ff);
	CAN_Filter_Mask_Config(&hcan1, CanFilter_1|CanFifo_0|Can_STDID|Can_DataType,0x202,0x3ff);
	CAN_Filter_Mask_Config(&hcan1, CanFilter_2|CanFifo_0|Can_STDID|Can_DataType,0x203,0x3ff);
	CAN_Filter_Mask_Config(&hcan1, CanFilter_3|CanFifo_0|Can_STDID|Can_DataType,0x204,0x3ff);
	
	/*CAN2*/
	CAN_Filter_Mask_Config(&hcan2, CanFilter_15|CanFifo_1|Can_STDID|Can_DataType,0x201,0x3ff);
	CAN_Filter_Mask_Config(&hcan2, CanFilter_16|CanFifo_1|Can_STDID|Can_DataType,0x202,0x3ff);
  CAN_Filter_Mask_Config(&hcan2, CanFilter_17|CanFifo_1|Can_STDID|Can_DataType,0x203,0x3ff);
	CAN_Filter_Mask_Config(&hcan2, CanFilter_18|CanFifo_1|Can_STDID|Can_DataType,0x204,0x3ff);
	
}

/**
	* @brief  系统任务初始化
	* @retval None
	*/
void RTOS_Init(void)
{
	/*串口遥控任务*/
	xTaskCreate(RC_Task, "rc_task", Small_Stack_Size, NULL, PrioritySuperHigh, &RC_Task_Handler); 
	/*底盘任务*/
	xTaskCreate(Chassis_Task, "chassis_task", Normal_Stack_Size, NULL, PriorityHigh, &Chassis_Task_Handler); 
}

/*=========================================================中断回调函数=========================================================*/
/**
	* @brief  dr16串口中断回调函数
	* @retval None
	*/
static void dr16_call_back(uint8_t *buf, uint16_t len)
{
	static BaseType_t* xHigherPriorityTaskWoken;
	static USART_COB	DR16_Port = {0};
	if(len == RC_FRAME_LENGTH)
	{
			DR16_Port.port_num = 4;
			DR16_Port.address = buf;
			xTaskNotifyFromISR(RC_Task_Handler, (uint32_t) &DR16_Port, eSetValueWithOverwrite, xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);		//如果必要，进行一次任务切换
	}
}

/**
	* @brief  CAN1接收中断回调函数
	* @retval None
	*/
static void User_CAN1_RxCpltCallback(CAN_RxBuffer *CAN_RxMessage)
{
	Driver_motor_DatePrcess_IT(CAN_RxMessage->header.StdId, CAN_RxMessage->data);
}

/**
	* @brief  CAN2接收中断回调函数
	* @retval None
	*/
static void User_CAN2_RxCpltCallback(CAN_RxBuffer *CAN_RxMessage)
{
	Steer_motor_DatePrcess_IT(CAN_RxMessage->header.StdId, CAN_RxMessage->data);
}

/*=========================================================任务函数=========================================================*/
/** 
	* @brief 遥控解包任务 
 **/
void RC_Task(void *p_arg)
{
	static USART_COB* RCPort;
	while(1)
	{
		if(xTaskNotifyWait(0x00000000, 0xFFFFFFFF, (uint32_t *) &RCPort, portMAX_DELAY) == pdTRUE)
		{
			if(RCPort->port_num == 4)
			{
				dr16_DatePrcess(RCPort->address);
			}
		}
	}
}
/** 
	* @brief 底盘任务 
 **/
void Chassis_Task(void *p_arg)
{
	TickType_t xLastWakeTime_t = xTaskGetTickCount();
	Chassis_Init(&chassis_control);
	while(1)
	{
    vTaskDelayUntil(&xLastWakeTime_t,CHASSIS_TIM);
		Chassis_Loop(&chassis_control);
		CAN_CMD_DRIVER(chassis_control.drive_motor[0].set_current, chassis_control.drive_motor[1].set_current,
									 chassis_control.drive_motor[2].set_current, chassis_control.drive_motor[3].set_current);
		CAN_CMD_STEER(chassis_control.steer_motor[0].set_current, chassis_control.steer_motor[1].set_current,
									chassis_control.steer_motor[2].set_current, chassis_control.steer_motor[3].set_current);
	}
		
}
/*                                                                                                                                                                                                                                                                                                                                                                                                        
   风暴与你同在、、                                                                                                                                                                                                                                                                                                                                   .!!                                                                       
                                                                                                                                                                                                                                                                                                                                     7G#Y                                                                       
                                                                                                                                                                                                                                                                                                                                   ^5#B?                                                                        
                                                                                                                                                                                                                                                                                                                                  ?B#P~                                                                         
                                                                                                                                                                                                                                                                                                                                ^5#B?.                                                                          
                                                                                                                                                                                                                                                                                                                               ?B#P~                                                                            
                                                                                                                                                                                                                                                                                                                             ^5#B?.                                                                             
                                                                                                                                                                                                                                                                                                                            ?B#P~                                                                               
                                                                                                                                                                                                                                                                                                                          ^5#B?.                                                                                
                                                                                                                                                                                                                                                                           :^~!!!!~^.                                    ?B#P~                                                                                  
                                                                                                           ^!.                                                                                                                                                          ^7Y5555Y55555J!:                               ^5#B?.                                                                                   
                                                                          .                             .!Y55P!                                                                                                                                                       .?5YYYYYYYJJJJJY55Y!:                           ?B#P~                                                                                     
                                                                        ^JPJYY^                       ^JPY!::!P5^                                                                                                                                                    ~YYYYYYYJY555PP55YJY55Y!:                    ::^P#B?.                                                                                      
                                                                     :755?~YB#B?.                  .755?^:.:~?P5~                                                                                                                                                  .?5YYYYYYJPGPB####GPP5JYY55J!:            7Y7::Y7YGG~                                                                                        
                                                                   ~YPJ~::::~5B#G7.              ^JPY!:..:7YP?^                                                                                                                                                   ~YYYYYYYY?GPP@@@@@@@#PG5JYYYY55Y!^       ^YJ~!J5J!!?J^                                                                                        
                                                                :?557^::::::::7PBBP~  .       :755?^:.:~JPY!.                                                                                                                                                   .?5YYYYYYYY?#5#GB@@@@@@GPB?YYYYYYY55Y!:   75!:.::^!?YY^                                                                                         
                                                             .~YPJ~:::::::::::::?G#BYYJ^Y?. ~YPJ~:..^755?:                                                                                                                                                     ~YYYYYYYYYYY?GGPG?P#&&@BPBYJYYYYYYYYYY55J7YJ^....::::^!YY:                                                                                       
                                                           :?557^::::::::::::::::^JG#BJ^~5PP57^..:~JPY~                                                                                                                                                      .?5YYYYYYYYYYYY?PGGGPGBGGGGYJYYYYYYYYYYYYY55!::::..:...:?Y^                                                                                        
                                                        .~YBB?:.:::::::::::::::::::~YBBG7:!P5~:^?557:                                                                                                                                                       ~YYYYYYYYYYYYYYYY7J5PPPPP5YJJYYYYYYYJ?JYYY55J!^::..:::.!Y?.                                                                                         
                                                      ^?G#@@&BY~:::::::::::::::::::::!PBBP!:7P5PJ^                                                                                                                                                        .?5YYYYY?7?JYYYYY?^..!7YJJJJYYYYYYYYY7:.:~7JYY555J7^:::^?Y^                                                                                           
                                                   .!5B&@@@@@@&BJ^:::::::::::::::::::::7G#BY~:JG?.                                                                                                                                                        Y5YYYYY7^  ~7YY5Y7~..~JYYYYYYYYYYYYJ~.    .:~7JY5555J!!YPY!:                                                                                          
                                                 ^JG&@@@@@@@@@@@&G7:::::::::::::::::::::^JG#GJ^~5~                                                                                                                                                       .PYYYYYY?!^^!JY?!?JYJ?YYYYYYYYYYYYY7:.        .:~7JY55555YY55Y7:                                                                                       
                                              .75#&@@@@@@@@@@@@@@@#P!:::::::::::::::::::::~YB#G55:                                                                                                                                                        55YYYYYYYYJYY7:  ~7Y5YYYYYYYYYYYJ~.  :7??!:     .:~7JYYYYYYYY55Y7:                                                                                    
                                            ~JG&@@@@@@@@@@@@@@@@@@@@#Y~:::::::::::::::::::::!5BBP!                                                                                                                                                        7PYYYYYYYYYYYJ7^^7YYJ7?YYYYYYYY7:.   :JY?7^        .:~7JYYYYYYYY55Y7:                                                                                 
                                         :7P#&@@@@@@@@@@@@@@@@@@@@@@@&BJ^:::::::::::::::::::::7PBB5~                                                                                                                                                       JPYYYYYYY7~~?JYJYY7^  ~7YYYYJ~.    :::!7!!!.        .:7YYYYYYYYYYY55Y7:                                                                              
                                      .~YB&@@@@@@@@@@@@@@@@@@@@@@@@@@@@&G?:::::::::::::::::::::^?G#BY:                                                                                                                                                      J5YYYYY7^  ^7YYYY?!::!JYYY7:.      .:~~~^!7~^:    .^JYYYYYYYYJJJJJJY55Y7:                                                                           
                                    :?P#@@@@@@@@@@@@@@@@@@@@@5?&@@@@@@@@@#P7:::::::::::::::::::::^YB#G?:                                                                                                                                                     ^7YYYYJ?!~?YYYYYYYYJYYYJ~^   ...     .^~~^JY7  .:7YYYYYYYYJY5PPPPP5YJY55Y7:                                                                        
                                 .!YB&@@@@@@@@@@@@@@@@@@@@@@&: :Y@@@@@@@@@@#5~:::::::::::::::::::::~5BB7                                                                                                                                                       .^7Y5YYYYYYYYYYYYYYY!~GGJ~.  .:^      :!~.  .^JYYYYYYYY?PGPG####BPP5JYY5P7                                                                       
                               ^?G#@@@@@@@@@@@@@@@@@@@@@&GP&5    ^P@@@@@@@@@&BY^::::::::::::::::::::!GG~                                                                                                                                                          .^7YYYYYYYYYYYYY?.:!YBBGY~.     ..     .:7YYYYYYYYY?GGP#@@@@@@&PG5JYYYP?                                                                      
                            .!5#&@@@@@@@@@@@@@@@@@@&B57^.  :!: ^^  !B@@@@@@@@@&G?^:::::::::::::::^?55!.                                                                                                                                                              .^7YYYYYYYYYYYY?~~55GBBGY~.  ..:.. .^JYYYYYYYYYY?#5B&#@@@@@@BPG?YYYYG^                                                                     
                          ^JG&@@@@@@@@@@@@@BPP@@@@#~     ..  :^G@Y.  7#@@@@@@@@@&P7::::::::::::!YPJ^                                                                                                                                                                    .^7YYYYYYYYYYY55Y555GBBGY~.  .^:7YYYYYYYYYYYY?PGPBYPGB@@#PG5JYYYYP7                                                                     
                       :7P#&@@@@@@@@@@@@@@&GYPB@@@@#?:!JG&#?.  !B@B:  ?@@@@@@@@@@@#5!:::::::~?55!.                                                                                                                                                                         .^7JYYYYYYYYYYYYY5Y5GB#GY~.^JYYYYYYYYYYYYYY?5GGGPPGBGPGYJYYYYYP~                                                                     
                     ~JB&@@@@@@@@@@@@@@@@@@@BP5PP@@@@@@@##@7^^   ~^ 7PGB#&@@@@@@@@@&BY~:::!Y5?^                                                             ..                                                                                                                .^7JYYYYYYYYYYYYY7:!YP7!YYYYYYJYYYYYYYY?!7?Y5PPP55YJJYYYYY5?                                                                      
                  :?P#@@@@@@@@@@@@@@@@@@@@@@@@PPYB&@@@@@P.7  .!7^::!BBBBBBBB&@@@@@@@@&BJJPY!.                                                  .:^~!!7?JY55PPJ.                                                                                                                  .^7JYYYYYYYYYYY?~:^?YYYYYY??J5P5YYJ7:  ~7YJJJJJYYYYYYYY~                                                                       
                  ^5#&@@@@@@@@@@@@@@@@@@@@@@@@@@PP5PB@@@@!    5@@&@&BBBBBBBBBB#@@@@@@@#P?:                                             .:^!?J5PGGBBB###BPY7~:                                                                                                                       .^7JYYYYYYYYYYYYYYYY5GGBBBBBBBPYJ7^^?YYYYYYYYYYYY5?:                                                                        
                    ~P#@@@@@@@@@@@@@@@@@@@@@@@@@@&#55P&@@B JY:#@@@@@#BBBBBBBBBBB#@@&GJ~                                          .:~7J5PGBBBBBBBBBBG5?~:                                                                                                                               .^7JYYYYYYYYYY5PGBBBBBBBBBBBJ?JYYYYYYYYYYYYYYY~                                                                          
                      7G&@@@@@@@@@@@@@@@@@@@@@@@@@@&555&@@P#@&@@@@@@@#BBBBBBBBBBBBB7.                                       .:~?YPGBB##BBGBBBBBBP?~.                                                                                                                                      .^7JYYYYYYPBBBBBBBBBBBBBP:~?YYYYYYYYYYYY5?:                                                                           
                       .?B&@@@@@@@@@@@@@@@@@@@@@@@@@&G55GB@@@@@@@@@@@@&BBBBBBBBBBBB?                                    .^7YPGB##BBGG5YJYPBBB57^                                                                                                                                              ^7JYY5BBBBBBBBBBBBBP?!JYY!~!?JYYYYYY~                                                                             
                         :YB&@@@@@@@@@@@@@@@@@@@@@@@@@&GPYG@@@@@@@@@@@@@&BBBBBBBBBB!                                .^75GBB#BBGP5Y?7!!JPBBP?^                                                                                                                                                    ^7YBBBBBBBBBBGJ7?YY5J!:  ~7YYY5?:                                                                              
                           !G#&@@@@@@@@@@@@@@@@@@@@@@@@@#P5P&@@@@@@@@@@@@#PGBBBBP?^                              :!YPBBBBBGPY?7!!!!!JGBBP!.                                                                                                                                                         !PBBBBBBGY^.~?YYYYJ?!!JYYYY~                                                                                
                           ?BBG#@@@@@@@@@@@@@@@@@@@@@@@@@@&@@@@@@@@@@@&BY~ !BBBBP^                            :75GBBBBGPY?7!!!!!!!!5BBG7.                                                                              ..::......                                                                    5BBBG55YJ??YYYYYYYYYYYY5?:                                                                                 
                          .JBY~?G&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#P?:    ~GBBBG^                        :75BBBBBG5?7!!!!!!!!!!!PBBG^                                                                                !J5PGGGGGPP5YYJ???7!!~^^:..                                                  JBBBG^:7JY55YYYYYYYY555Y~                                                                                   
                           .!P5!~YB&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&BY~.       ~BBBBG:                     ^JGBBBBGY?!!!!!!!!!!!!!!YBBB^                                                                                    .:~7?J5PGB#####BBBBBBBGPP5Y?7!^:..                                       !BBBB!    ^!?JYYYYYJ?7!:                                                                                     
                             .?GY~?G#&@@@@@@@@@@@@@@@@@@@@@@@@&#P7:           7BBBB5.                  !5BBBBG5?!!!!!!!!!!!!!!!!!GBBY                                                                                             .^~7J5PGBBBG5555PGGBBBBBGP5Y?!~:.                               :GBBBJ                                                                                                        
                               :YG5GBG#@@@@@@@@@@@@@@@@@@@@@&GJ^               JBBBBJ                ~5BBBBGJ7!!!!!!!!!!!!!!!!!!!GBBY                                                                                                   .:~7JPGGPY7!!77?JY5PGB##BBG5J7^.                          5BBBP.                                                                                                        
                                 ^.:^.7G&@@@@@@@@@@@@@@@@&#5!.                  5BBBB?             ^5BBBBPJ!!!!!!!!!!!!!!!!!!!!!!5BBG^                                                                                                        :!JPBGY7!!!!!!!7?J5PGB##BG5J!:.                    ?BBBB^                                                                                                         
                                       :JB&@@@@@@@@@@@@&GJ^                     :GBBBB7           7GBBBGJ!!!!!!!!!!!!!!!!!!!!!!!!7GBBP:                                                                                                          .~YBB57!!!!!!!!!!!7JYPGB##BPJ!:                ^GBBB?                                                                                                          
                                         ^Y#&@@@@@@@&B5!.                        ~GBBBB7        .YBBBB57!!!!!!!!!!!!!!!!!!!!!!!!!!7GBBG!                                                                                                            7BBG7!!!!!!!!!!!!!!!7J5GB##G57^             5BBBG.                                                                                                          
                                           ~P#@@@@#G?^                            ~GBBBB!      .5BBBBJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!75BBB5~                                                                                                           5BBY!!!!!!!!!!!!!!!!!!!?YPBB#B57.         ?BBBB?                                                                                                           
                                            .7G#BY~.                               ~BBBBB!    .5BBBBJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?PB#BP7:                                                                                                       ~GBB?!!!!!!!!!!!!!!!!!!!!!!7JPBBBGJ:      ^GBBB?                                                                                                            
                                              :!:                                   !BBBBB~   ?BBBBJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?5GB#GY!:                                                                                                 :!YBBG?!!!!!!!!!!!!!!!!!!!!!!!!!!?5GBBGJ.    5BBB5.                                                                                                            
                                                                                     !BBBBG~ .GBBBP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7JPGB#B5?~:                                                                                         :~?PB#B5J!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!75BBBG!  7BBBG^                                                                                                             
                                                                                      7BBBBG^~BBBBJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7J5GB#BG5J!^.                                                                               .^!JPBBBG5?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?PBBB?^GBBB!                                                                                                              
                                                                                       7BBBBGYBBBB?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?J5GB##BG5?!~:.                                                                   .:~7J5GBBBPYJ7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!5BBBGBBBY                                                                                                               
                                                                                        ?BBBBBBBBB?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7JY5PBB#BBGP5J?7~^:..                                                 .:^~7JYPGBBBGP5J?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!PBBBBBG.                                                                                                               
                                                                                         ?BBBBBBBBY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7?JY5PGGBB##BBGPP5YJ?7!~~^^:::.....             ....::^^~~!7?JY5PGBBBBGG5YJ?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JBBBBB~                                                                                                                
                                                                                          JBBBBBBBG7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!77?JY5PPGBBBB###BBBBBGGGGPPPPPPPPPPPPPPPPGGGBBBBBBBBGGPP5YJ??7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?BBBBJ                                                                                                                 
                                                                                           JBBBBBBBP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!77???JJYY555PPPPPGGGGGGGGGPPPPP555YYJJ???77!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!5BBBP.                                                                                                                 
                                                                                            JBBBBBBB5!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!5BBBB^                                                                                                                  
                                                                                             YBBBBBBBP7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7PBBBB7                                                                                                                   
                                                                                             .YBBBBBBBGY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JGBBBB5                                                                                                                    
                                                                                              .YBBBBBBBBP?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!^^^^^!!!!!!!!!!!!!!!!!!!!!!!?PBBBBBG:                                                                                                                    
                                                                                               .5BBBBBBBBBPJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!^^^^^^^^^~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!^^:!57:!!!!!!!!!!!!!!!!!!!!!?5BBBBBBB!                                                                                                                     
                                                                                                .5BBBBGPBBBBGY7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:~PPPPP7:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:!PG#J:!!!!!!!!!!!!!!!!!!7JPBBBGGBBBJ                                                                                                                      
                                                                                                 .5BBBB?!5BBBBG5J7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:!BBBB#J:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:!BBBJ:!!!!!!!!!!!!!!!!?5GBBBP77BBBP.                                                                                                                      
                                                                                                  .5BBBB! ^JGBBBBG5J7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:~PP55P7:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:!BBBJ:!!!!!!!!!!!!!?YGB#BGY~ .PBBB^                                                                                                                       
                                                                                                   .5BBBB~  .!YGBBBBGPY?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:^!!!!7~:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:!BBBJ:!!!!!!!!!7J5GB#BG5!:   JBBB7                                                                                                                        
                                                                                                    .5BBBG~    :!YPBBBBBG5J?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:!BBBBBJ:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:!BBBJ:!!!!!7JYPBBBBPY!:     ~BBB5                                                                                                                         
                                                                                                     .5BBBG^      .JBBBBBBBBGPY7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:!BBBBB?:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~:!BBBJ:!?J5PBBBBBBBP?^      .PBBG:                                                                                                                         
                                                                                                      .5BBBP:    :YBBBGYYPGBBBBY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:!BBBBB?:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:!BBBJ:PBBBBGPY?JYPBBBP?:   ?BBB~                                                                                                                          
                                                                                                       .5BBBP.  ~GBBB57!!!7?JYJ7!!!!!!!!!!~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^:!BBBBB?:^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^:!BBBJ:PG5J?7!!!!!!7YGBBGJ:^GBB?                                                                                                                           
                                                                                                        .YBBBY ~BBBBJ!!!!!!!!!!!!!!!!!!YJ^^:?PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBBBBBGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPPBBBJ:!!!!!!!!!!!!!!!JGBBGPBBY                                                                                                                            
                                                                                                         .YBBBYGBBBJ!!!!!!!!!!!!!!!!!!~^?GPPGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGBBBBBBGGGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBP775BBBJ:!!!!!!!!!!!!!!!!75BBBB5.                                                                                                                            
                                                                                                           JBBBBBBY!!!!!!!!!!!!!!!!!!!~:7BBBBBP55BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG55GBG~^^!PPPPP?^^^5BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBY  ?BB#J:!!!!!!!!!!!!!!!!!!5BBB?                                                                                                                             
                                                                                                            ?BBBBB7!!!!!!!!!!!!!!!!!!!~:7BBBBB^ .GBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBJ  J#G^:!!~~~~~!!^:5#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGBY  ?#G57:!!!!!!!!!!!!!!!!!!?BBB5                                                                                                                             
                                                                                                             7BBBG!!!!!!!!!!!!!!!!!!!!~:7BBBBB^ .GBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGPPGPJ^^!!!!!!!!!^:?YGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG:.~GGPY7:^^!!!!!!!!!!!!!!!!!!7GBBP.                                                                                                                            
                                                                                                             :GBBB7!!!!!!!!!!!!!!!!!!!~:7BBBBB5JJ~~?BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB!:^~!!!!!!!!!~~::PBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB7~~JJ5BY7:^~~!!!!!!!!!!!!!!!!!!!7BBBP                                                                                                                             
                                                                                                              5BBBY!!!!!!!!!!!!!!!!!!!~:7BBB5?P#B!~!JJPBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBJ7^:!!!!!!!!!!!!!^:PBBBBBBYJYBBBBBBBBBBBBBBBBBBBBBBBB5JJ!~!BBJ7::~~!!!!!!!!!!!!!!!!!!!!!JBBBJ                                                                                                                             
                                                                                                              ^BBBBJ!!!!!!!!!!!!!!!!!!~:7BBB?:YBBB#5..7GPGBBBBBBBBBBBBBBBBBBBBBBBBBBJ7~~~~!!!!!!!!!!!!!~~!7GBBBG^.^PPGBBBBBBBBBBBBBBBBBBGPG7..5#BBP::~~!!!!!!!!!!!!!!!!!!!!!!7GBBG:                                                                                                                             
                                                                                                               !BBBBJ!!!!!!!!!!!!!!!!!~:7BBB?:~!!!GBGB7  5BBBBBBBBBBBBBBBBBBBBBBBBBB!:~!!!!!!!!!!!!!!!!!!^:~7GBBGB5  7BBBBBBBBBBBBBBBBBB5  ?BGBBG7!~~!!!!!!!!!!!!!!!!!!!!!!!?GBBG^                                                                                                                              
                                                                                                                !GBBB57!!!!!!!!!!!!!!!~:7BBB?:~~^:5GBBP55~:^GBBBBBBBBBBBBBBBBBBBGG?~~!!!!!!!!!!!!!!!!!!!!!~^:~7BBBG557:^^^^^^^^^^^^^^^^:~55GBGG!~~~!!!!!!!!!!!!!!!!!!!!!!!!JGBBP^                                                                                                                               
                                                                                                                 :5BBBGJ!!!!!!!!!!!!!!~:7BBB?:~!!!~~5GBBBJ7?GBBBBBBBBBBBBBBBBBB#J^^~!!!!!!!!!!!!!!!!!!!!!!!!!:~PGBBBB5777777777777777777JB#GP7^^^!!!!!!!!!!!!!!!!!!!!!!!!?PBBBJ.                                                                                                                                
                                                                                                                   !PBBBGY7!!!!!!!!!!!~:7BBB?:~!!!!!^~5PB###BBBBBBBBBBBBBBBBG55P?:~!!!!!!!!!!!!!!!!!!!!!!!!!!^^:!PPBBB###################GP7^~!!!!!!!!!!!!!!!!!!!!!!!!!JPBBB5~                                                                                                                                  
                                                                                                                    .7PBBBG5?!!!!!!!!!~:7BBB?:~!!!!!!!^~YYYYY5PPPPPPP5YYYYY5J^^^~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!^^:!5YYYYYYYYYYYYYYYYYYYY57^~!!!!!!!!!!!!!!!!!!!!!!!!7YGB#B5~                                                                                                                                    
                                                                                                                      .~YGBBBG5?!!!!!!~:7BBB?:~!!!!!!!!!^^^^^^~~~~~~~^^^^^^^~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!^^^^^^^^^^^^^^^^^^^^^^^^~!!!!!!!!!!!!!!!!!!!!!!!7JPB#BGJ^                                                                                                                                      
                                                                                                                         :75BB#BG5J7!!~:7BBB?:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?YPB#BGY!.                                                                                                                                        
                                                                                                                            ^75GB#BBG5?:7BBB?:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?J5GBBBPJ!.                                                                                                                                           
                                                                                                                               :~JBBB#5:7BBB?:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7?YPGBBBBBBY.                                                                                                                                              
                                                                                                                                 7BBG5J:7BBB?:J5?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7J5GBBBGP5J7JBBB!                                                                                                                                              
                                                                                                                                ^GBBJ!~:7BB#?:5#G7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JGGP5YJ7!!!!!!JBBP.                                                                                                                                             
                                                                                                                                7BBG7!~:!PPP7:7?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!PBB^                                                                                                                                             
                                                                                                                                ?BBG7!~^^^^^^^~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!5BB^                                                                                                                                             
                                                                                                                                ^BBBJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7777777777777777!!!!!77777!7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7GB5                                                                                                                                              
                                                                                                                                 ?BBB?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?JYJ77!~~^^!77^~~~^:~~~!!!!!7~^^~J!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!PBG^                                                                                                                                              
                                                                                                                                  JBBBY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7?JJYYYYYYY55Y555YJJJJJYJ7!!7J?~J?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?P#G^                                                                                                                                               
                                                                                                                                   !GBBGJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7777777??!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!75BBY:                                                                                                                                                
                                                                                                                                    .?G#BGY7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?5BB5~                                                                                                                                                  
                                                                                                                                      :?PB#BPJ7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?YGBBY~                                                                                                                                                    
                                                                                                                                        .~JGB#BPY?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7?5GBB57:                                                                                                                                                      
                                                                                                                                           .~JPB#BGPYJ7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7JYPBBPJ!:                                                                                                                                                         
                                                                                                                                               :!5BBBBBGPYJ7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!77JYPGBBPJ!^.                                                                                                                                                            
                                                                                                                                                 YBBBB55GBBBGP5YJ?7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7?JY5GBBBGBBBB^                                                                                                                                                                
                                                                                                                                                ~BBBBP. .^~7GBBBBBGGPYJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7?JJYY5PGGBBBBBY!^:.JBBB5                                                                                                                                                                
                                                                                                                                               :GBBBB!      ?BBBY7??JJJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JPPPPP55YY?5BBG.    .PBBBJ                                                                                                                                                               
                                                                                                                                               5BBBB5       .PBBP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!~?GBB7      !BBBB7                                                                                                                                                              
                                                                                                                                              7BBBBB^        :PBB5!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!YBBB7        5BBBG^                                                                                                                                                             
                                                                                                                                             ^GBBBB?          :PBBY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7YG#B5^         ^GBBBP.                                                                                                                                                            
                                                                                                                                            .5BBBBP.           .YBB5!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?5B#B5~            7BBBBY                                                                                                                                                            
                                                                                                                                            JBBBBB~              7G#P7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JPBBP7:               5BBBB!                                                                                                                                                           
                                                                                                                                           ~BBBBBY                :YBBY7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JG#GJ^                  ^BBBBG^                                                                                                                                                          
                                                                                                                                          .PBBBBG:                  ~5#BY7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!75BBJ:                     ?BBBB5.                                                                                                                                                         
                                                                                                                                          ?BBBBB!                     !5BB5?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!7PBG~                        5BBBBJ                                                                                                                                                         
                                                                                                                                         ~BBBBBY                        ^YGBGY7!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!5BB~                         ^BBBBB!                                                                                                                                                        
                                                                                                                                        .PBBBBG:                          :75BBPY?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!?BBJ                           ?BBBBG:                                                                                                                                                       
                                                                                                                                        JBBBBB!                              :75GBG5J?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!JBB^                           .5BBBBY                                                                                                                                                       
                                                                                                                                       ~BBBBBY                                  .~?5GBGP5J?7!!!!!!!!!!!!!!!!!!!!!!!?BB7                            ^GBBBB7                                                                                                                                                      
                                                                                                                                      .PBBBBG:                                      :~?YPBBBGPYJ?77!!!!!!!!!!!!!!!!!?GBY^                           7BBBBB^                                                                                                                                                     
                                                                                                                                      JBBBBB!                                           .:~7J5PGBBBGGP55YJJJ???777777?5BB5?^                         5BBBB5.                                                                                                                                                    
                                                                                                                                     ~BBBBBY                                                   .:^!7?JY55PPPGGGPPPPPP5YYJ?7^                         :GBBBB?                                                                                                                                                    
                                                                                                                                    .PBBBBG:                                                               ..........                                 !BBBBB~                                                                                                                                                   
                                                                                                                                    JBBBBB!                                                                                                            YBBBBP.                                                                                                                                                  
                                                                                                                                   ~BBBBBY                                                                                                             .PBBBBJ                                                                                                                                                  
                                                                                                                                  .PBBBBG:                                                                                                              ~BBBBB!                                                                                                                                                 
                                                                                                                                  JBBBBB!                                                                                                                ?BBBBG:                                                                                                                                                
                                                                                                                                 ~BBBBBY                                                                                                                 .PBBBBY                                                                                                                                                
                                                                                                                     .::::..    .PBBBBG:                                                                                                                  ^BBBBB7  .^!7JY555Y?~.                                                                                                                                
                                                                                                                 ^?5PGGGGGGGP5J7YBBBBB!                                                                                                                    7BBBBG?5GBBBBBBBBBBBP^                                                                                                                               
                                                                                                                JBBBBBBBBBBBBBBBBBBBBY                                                                                                                      JBBBBBBBBBBBBBBBBBB#!                                                                                                                               
                                                                                                               .5#BBBBBBBBBBBBBBBBBBP:                                                                                                                      ~GBBBBBBBBBBBBBBBG5!                                                                                                                                
                                                                                                                .75GGBBBBBBGGGPPPPPJ:                                                                                                                        :^~~^^^~~~~~!~^^.                                                                                                                                  
                                                                                                                   .:^^^^^::.......                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                     ...:::....                                                                  ....::...                                                                                                                                                                                                                      
                                                                                                ^!JYPPGGGGGGGGPP55Y?    :YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY7             :~!?Y5PPGGGGGGGGP5YJ7!^.                7YYYYYYYYYY55555555555YYJ?7!^.           7YYYYYYYYYYYYYYY.           :YYYYYYYYYYYYYYY?                                                                                                        
                                                                                             :?PBBBBBBBBBBBBBBBBBBBG.   ^BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB#J         :!JPGBBBBBBBBBBBBBBBBBBBBBBGY7^             5#BBBBBBBBBBBBBBBBBBBBBBBBBBBPY~         5#BBBBBBBBBBBBB#!           Y#BBBBBBBBBBBBB#5                                                                                                        
                                                                                            !GBBBBBBBBBBBBBBBBBBBBBB^   ~BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB7      .!5GBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB5!.          5BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB5:      .PBBBBBBBBBBBBBBB5          !BBBBBBBBBBBBBBBBJ                                                                                                        
                                                                                           !BBBBBBBBBBBBBGPPPPPGBBB#!   !BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB!    .7PBBBBBBBBBBBBBBGPPPPGGBBBBBBBBBBBBBBP!         5BBBBBBBBBBGGGGGGGGGBBBBBBBBBBBBBP.     :GBBBBBBBBBBBBBBBB!        ^GBBBBBBBBBBBBBBBB?                                                                                                        
                                                                                           PBBBBBBBBBBBY~:.  ...:^!?!   :~~^^^^^^^^:?BBBBBBBBBBB?::::::^^^^^.   ^PBBBBBBBBBBBBGJ!^..   .:^7YGBBBBBBBBBBBBJ.       5BBBBBBBBBB!.......:^?GBBBBBBBBBBB~     ^BBBBBBBBBBBBBBBBBP.      .PBBBBBBBBBBBBBBBBB7                                                                                                        
                                                                                           PBBBBBBBBBBB~                            ?BBBBBBBBBBB^              ^GBBBBBBBBBBBP!.             :JBBBBBBBBBBBBY       PBBBBBBBBBB^          ~BBBBBBBBBBB!     ~BBBBBBBBGGBBBBBBBB7      YBBBBBBBGPBBBBBBBBB!                                                                                                        
                                                                                           ~BBBBBBBBBBBG?:                          JBBBBBBBBBBG:             .PBBBBBBBBBBBY.                 ~BBBBBBBBBBBB!     .PBBBBBBBBBG:          !BBBBBBBBBBG.     7BBBBBBBB?YBBBBBBBBG.    7BBBBBBBB7JBBBBBBBBB~                                                                                                        
                                                                                            ~PBBBBBBBBBBBGY~.                       JBBBBBBBBBBP.             ?BBBBBBBBBBB5.                   ?BBBBBBBBBBB5     .GBBBBBBBBBG.       .^JBBBBBBBBBBG~      YBBBBBBBB~~BBBBBBBBB?   ^BBBBBBBB5 JBBBBBBBBB^                                                                                                        
                                                                                             .7PBBBBBBBBBBBBP?^                     YBBBBBBBBBB5              PBBBBBBBBBBB~                    :BBBBBBBBBBBG.    :GBBBBBBBBBP  JYYY5PGBBBBBBBBBBGJ:       PBBBBBBBB^ 5BBBBBBBBG. .5BBBBBBBG: YBBBBBBBBB^                                                                                                        
                                                                                                ~YGBBBBBBBBBBBB5!.                  5BBBBBBBBBBY             .GBBBBBBBBBBB:                    :BBBBBBBBBBBG.    :BBBBBBBBBB5  ^BBBBBBBBBBBBGPY!:        :GBBBBBBBG. ~BBBBBBBBB! ?BBBBBBBB7  5BBBBBBBBG:                                                                                                        
                                                                                                  :?PBBBBBBBBBBBBP!                .PBBBBBBBBBBJ              PBBBBBBBBBBB~                    7BBBBBBBBBBB5     ^BBBBBBBBBBY   !BBBBBBBBBB5:            ^BBBBBBBBP   YBBBBBBBB5^GBBBBBBBY   PBBBBBBBBG.                                                                                                        
                                                                                                    .~YBBBBBBBBBBBBJ.              .GBBBBBBBBBB?              JBBBBBBBBBBB5.                  ^GBBBBBBBBBBB!     !BBBBBBBBBBJ    JBBBBBBBBBB7            !BBBBBBBB5   ^BBBBBBBBGPBBBBBBBG:  .PBBBBBBBBG.                                                                                                        
                                                                                                       ^5BBBBBBBBBB#?              :BBBBBBBBBBB7              :GBBBBBBBBBBB5:                !GBBBBBBBBBBBJ      7BBBBBBBBBBJ    .5BBBBBBBBBB!           JBBBBBBBBJ    5BBBBBBBBBBBBBBBB!   .GBBBBBBBBP.                                                                                                        
                                                                                         ^~:            ?BBBBBBBBBBB5              ~BBBBBBBBBBB!               !BBBBBBBBBBBBGJ~.          :7PBBBBBBBBBBBBY.      JBBBBBBBBBB?     :GBBBBBBBBBB!          5BBBBBBBB?    ~BBBBBBBBBBBBBBBJ    :GBBBBBBBBP                                                                                                         
                                                                                         !BGP5J?7!~~~!?5BBBBBBBBBBBB7              7BBBBBBBBBBB~                ~PBBBBBBBBBBBBBG5J?7!!7?YPBBBBBBBBBBBBBG7        5BBBBBBBBBB7      !BBBBBBBBBBB!        .GBBBBBBBB!     5BBBBBBBBBBBBBP.    :BBBBBBBBBP                                                                                                         
                                                                                         ^BBBBBBBBBBBBBBBBBBBBBBBBBJ               JBBBBBBBBBBB~                 .7PBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGJ:        .PBBBBBBBBBB7       JBBBBBBBBBBB~       ^BBBBBBBBB~     !BBBBBBBBBBBBB^     ^BBBBBBBBBP                                                                                                         
                                                                                         .GBBBBBBBBBBBBBBBBBBBBBB5~                5BBBBBBBBBBB^                   .~YGBBBBBBBBBBBBBBBBBBBBBBBBBBBG57:          ^BBBBBBBBBBB!       .GBBBBBBBBBBB~      7BBBBBBBBB:      PBBBBBBBBBBB?      ~BBBBBBBBB5                                                                                                         
                                                                                          5BBBBBBBBBBBBBBBBBBG5?^                 .GBBBBBBBBBBB^                      .~7YPGBBBBBBBBBBBBBBBBBGPY?~:             !BBBBBBBBBBB!        !BBBBBBBBBBBB~     YBBBBBBBBG:      !BBBBBBBBBB5       7#BBBBBBBBP                                                                                                         
                                                                                          .:^^~!77??JJJ??7!~^.                    .^^^^^^^^^^^^.                           .:^!77??JJJ??77!~^.                  :~^^^^^^^^^~.         ^^^^^^^^^^^~^     ^^^^^^^^^^        ^^^^^^^^^~.       :~^^^^^^^^^                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                       !JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ~       :JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ!!JJJJJJJJJJJ?.     ~JJJJJJJJJJJJJ!                ~JJJJJJJJJJJ!      7JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ!      ~JJJJJJJJJJJJJJJJJJJJJJJJ7!JJJJJJJJJJJ?.       7JJJJJJJJJJJJJJJJJJJJJJJJJJJJ?~?JJJJJJJJJJJ^     ~JJJJJJJJJJJ7                                                   
                                      ^&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@B7.       5@@@@@@@@@@@@@@@@@@@@@@@@@@@G7^#@@@@@@@@@@@Y     .B@@@@@@@@@@@@@@?              .#@@@@@@@@@@@7     ~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Y:     .#@@@@@@@@@@@@@@@@@@@@@@B?:G@@@@@@@@@@@5       !@@@@@@@@@@@@@@@@@@@@@@@@@@@#J:Y@@@@@@@@@@@#.    .#@@@@@@@@@@@J                                                   
                                      5@@@@@@@@@@@B5PPPPPPPPPPPPPPPPPPPPPPPPP5!         ~&@@@@@@@@@@@GPPPPPPPPPPPPPY^  ?@@@@@@@@@@@#:     ?@@@@@@@@@@@@@@@@7             J@@@@@@@@@@@G      ?GPPPPPPPPPPPPPG@@@@@@@@@@@@GPPPPPPPPPPPPP5^       J@@@@@@@@@@@&P5555555P5!  !@@@@@@@@@@@&:       G@@@@@@@@@@@BPPPPPPPPPPPPP5!. :&@@@@@@@@@@@7     ?@@@@@@@@@@@#.                                                   
                                     ~@@@@@@@@@@@&^                                     P@@@@@@@@@@@G                 :#@@@@@@@@@@@J     :#@@@@@@@@@@@@@@@@&!           :#@@@@@@@@@@@!                     ?@@@@@@@@@@@G                      :#@@@@@@@@@@@?            .B@@@@@@@@@@@J       7@@@@@@@@@@@&^                 5@@@@@@@@@@@B.    :#@@@@@@@@@@@?                                                    
                                     P@@@@@@@@@@@5                                     ~@@@@@@@@@@@@~                 J@@@@@@@@@@@#.     J@@@@@@@@@@@@@@@@@@&~          Y@@@@@@@@@@@P                     :#@@@@@@@@@@@!                      Y@@@@@@@@@@@B.            7@@@@@@@@@@@#:      .B@@@@@@@@@@@Y                 ^&@@@@@@@@@@@!     J@@@@@@@@@@@B.                                                    
                                    !@@@@@@@@@@@&^                                     G@@@@@@@@@@@P                 :&@@@@@@@@@@@?     :&@@@@@@@@@@@#@@@@@@@#^        ^&@@@@@@@@@@@~                     J@@@@@@@@@@@P                      ^&@@@@@@@@@@@7            .B@@@@@@@@@@@J       7@@@@@@@@@@@&:                 P@@@@@@@@@@@G     :&@@@@@@@@@@@7                                                     
                                    G@@@@@@@@@@@Y                                     !@@@@@@@@@@@&^                 Y@@@@@@@@@@@B.     Y@@@@@@@@@@@G.P@@@@@@@B:       5@@@@@@@@@@@5                     :&@@@@@@@@@@@~                      5@@@@@@@@@@@B.            ?@@@@@@@@@@@#.      .B@@@@@@@@@@@J                 ~@@@@@@@@@@@@!     Y@@@@@@@@@@@G                                                      
                                   !@@@@@@@@@@@#:                                    .G@@@@@@@@@@@5                 ^&@@@@@@@@@@@7     ^&@@@@@@@@@@@! .G@@@@@@@G.     ^&@@@@@@@@@@&^                     Y@@@@@@@@@@@P                      ^&@@@@@@@@@@@7 ...........:#@@@@@@@@@@@?       ?@@@@@@@@@@@#:                 P@@@@@@@@@@@P     ^&@@@@@@@@@@@!                                                      
                                  .B@@@@@@@@@@@J                                     7@@@@@@@@@@@&^                 5@@@@@@@@@@@G      5@@@@@@@@@@@G   .G@@@@@@@P.    5@@@@@@@@@@@Y                     ^&@@@@@@@@@@&^                      P@@@@@@@@@@@@##############@@@@@@@@@@@B.      :#@@@@@@@@@@@J                 !@@@@@@@@@@@@~     5@@@@@@@@@@@P                                                       
                                  7@@@@@@@@@@@#.                                    .B@@@@@@@@@@@Y                 ~@@@@@@@@@@@@!     ~&@@@@@@@@@@@~    :B@@@@@@@5   ~@@@@@@@@@@@&^                     5@@@@@@@@@@@5                      ~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@7       J@@@@@@@@@@@#.                 G@@@@@@@@@@@5     ~@@@@@@@@@@@@~                                                       
                                 .B@@@@@@@@@@@?                                     ?@@@@@@@@@@@#:                 P@@@@@@@@@@@P      P@@@@@@@@@@@P      :B@@@@@@@Y  P@@@@@@@@@@@J                     ~@@@@@@@@@@@&^                      P@@@@@@@@@@@G~~~~~~B@@@@@@@@@@@@P~~~~~~       :&@@@@@@@@@@@?                 7@@@@@@@@@@@&^     P@@@@@@@@@@@P                                                        
                                 ?@@@@@@@@@@@B.                                    .#@@@@@@@@@@@J                 ~@@@@@@@@@@@@~     ~@@@@@@@@@@@&^       ^#@@@@@@@J!@@@@@@@@@@@#:                     P@@@@@@@@@@@Y                      !@@@@@@@@@@@@~      ~@@@@@@@@@@@@&^            Y@@@@@@@@@@@B.                .B@@@@@@@@@@@Y     ~@@@@@@@@@@@&^                                                        
                                :#@@@@@@@@@@@7                                     J@@@@@@@@@@@#:                 G@@@@@@@@@@@P      G@@@@@@@@@@@5         ^#@@@@@@@&@@@@@@@@@@@J                     !@@@@@@@@@@@#:                      G@@@@@@@@@@@5        Y@@@@@@@@@@@@G.          ^&@@@@@@@@@@@7                 ?@@@@@@@@@@@&:     G@@@@@@@@@@@5                                                         
                                J@@@@@@@@@@@G                                     :#@@@@@@@@@@@?                 !@@@@@@@@@@@&^     !@@@@@@@@@@@&^          ~&@@@@@@@@@@@@@@@@@#.                     G@@@@@@@@@@@J                      7@@@@@@@@@@@&^        .B@@@@@@@@@@@@?          5@@@@@@@@@@@G                 .#@@@@@@@@@@@J     !@@@@@@@@@@@&^                                                         
                               :#@@@@@@@@@@@7.............................:.      Y@@@@@@@@@@@#^.::::::::::::::::B@@@@@@@@@@@5     .G@@@@@@@@@@@Y            !&@@@@@@@@@@@@@@@@?                     !@@@@@@@@@@@#.                     .B@@@@@@@@@@@Y          ~&@@@@@@@@@@@&^        ~@@@@@@@@@@@@7.:::::::::::::::.J@@@@@@@@@@@#:    .G@@@@@@@@@@@5....................:.                                    
                               Y@@@@@@@@@@@@&###########################&&P^     ^&@@@@@@@@@@@@&&&&&&&&&&&&&&&&&&@@@@@@@@@@@&^     7@@@@@@@@@@@&:             !@@@@@@@@@@@@@@@B.                    .B@@@@@@@@@@@?                      ?@@@@@@@@@@@&:           J@@@@@@@@@@@@P        P@@@@@@@@@@@@&&&&&&&&&&&&&&&&&&@@@@@@@@@@@@?     7@@@@@@@@@@@@&#&&&&&&&&&&&&&&&&&&&G~                                    
                              ^&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#?.      Y@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Y     .B@@@@@@@@@@@J               7&@@@@@@@@@@@@@7                     7@@@@@@@@@@@B.                     .B@@@@@@@@@@@J            .G@@@@@@@@@@@@7      ~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@B.    .B@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&J.                                     
                              .^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^.        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^.     .^^^^^^^^^^^^.                :^^^^^^^^^^^^^                      :^^^^^^^^^^^:                      .^^^^^^^^^^^^.             .^^^^^^^^^^^^:      :^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^:     .^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^:                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
*/
